name = "RokuEnhanced"
author = "Aikovdp"
version = "1.0.0-alpha.4+1.20.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12716cccbe0d39ef10cc78bab108ae6125bc71c223559b8fc5b172d0e0499a99"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
