name = "RokuEnhanced"
author = "Aikovdp"
version = "1.0.0-alpha.4+1.20.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9462af3d38d33d59e39f7f6d883968893629bbd6483ef72f3f9af535684e2d08"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
