name = "RokuEnhanced"
author = "Aikovdp"
version = "1.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ad44a303d738855a5a2ca597ed1b809bee65e438e49df98ce35145e3aa072d8"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
